[build]
  command = "npm run build"
  publish = "build"
[[headers]]
  for = "/sitemap.xml.txt"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
